### PR TITLE
Added merge and push scripts

### PR DESCRIPTION
**Pull request by arosso3**

### CODE REVIEW

**Comment by kstola2** [comment]
Hey can you describe how this works? It looks fine I just want to be able to explain it.

**Comment by arosso3** [comment]
They are scripts that run the git pull upstream master and git push origin master commands respectively
then wait for the user to press enter so that the output stays in the screen

**Comment by arosso3** [comment]
I added committing to the push script so that now when it is run it will go through all files you have changed, ask if you want to commit them, allow you to put a summary for your commit then commit the files and push them

**Comment by kstola2** [comment]
Does the upstream work? I'm only asking cause I've never ran that command before. It looks good to me though.

**Comment by arosso3** [comment]
I've been using it for a few weeks now and haven't had any issues

**Pull request merged**
