### PR TITLE
Added data function and test data

### PR DESCRIPTION
**Pull request by jjex05**

### CODE REVIEW

**Comment by kstola2** [comment]
I'm unable to do a test-merge to my repository because of merge conflicts. I need to look into what's wrong here because someone else is having the same issue.

**Comment by kstola2** [comment]
I found out this is a branch so I need to remove it.

**Comment by jjex05** [comment]
What do you mean?

**Comment by kstola2** [comment]
The development process we are doing uses forks versus branching. We are trying to avoid confusion by having everyone just pull from one master branch.

**Pull request closed without merging**
