### PR TITLE
Updated bash scripts

### PR DESCRIPTION
**Pull request by arosso3**
Merge script now pushes just pulled changes to remote repo
Added more options for saying yes to options in commit/push scripts

### CODE REVIEW

**Comment by wilt00** [comment]
I missed the last PR, but can these scripts be renamed so they don't have spaces in the filenames?

**Comment by arosso3** [comment]
Sure

**Comment by arosso3** [comment]
Check if you have an upstream set with `git remote -v` if it is set properly you should see:
`upstream        https://github.com/SIGBlockchain/Project.git (fetch)`
`upstream        https://github.com/SIGBlockchain/Project.git (push)`
If you don't see these try running  `git remote add upstream https://github.com/SIGBlockchain/Project.git
`

**Comment by kstola2** [comment]
Yeah I have that.

**Comment by arosso3** [comment]
You could try removing the upstream with `git remote rm upstream` and then re-adding it.

**Pull request merged**
