### PR TITLE
Update data_structures/keys.py

### PR DESCRIPTION
**Pull request by jjex05**
The requirements for keys.test.py were already made before I started issue.

### CODE REVIEW

**Comment by jldistefano** [comment]
I believe the point of this issue is to type  `pip install ecdsa` into your console, so any further development on keys.py will work

**Comment by kstola2** [comment]
Also, keys and keys.test are blank in dev. All development should focus on the dev branch and not the master branch. Pretend master doesn't exist.

**Comment by jjex05** [comment]
screenshot 177

**Comment by jjex05** [comment]
Is the version that I currently have, the reason why the keys isn't working, because the keys.test works.

**Comment by jjex05** [comment]
As for the dev, I am getting this issue.

**Comment by jjex05** [comment]
screenshot 178

**Comment by jjex05** [comment]
screenshot 179

**Comment by kstola2** [comment]
I'd suggest deleting your branch and local repo and pulling from dev. Have you tried that?

**Comment by kstola2** [comment]
Your jjex5 branch is up to date with dev because it is blank. That's the one that needs to be worked on.

**Comment by jjex05** [comment]
Yes, I followed the steps we did on Sunday. This is what I did...

**Comment by jjex05** [comment]
1. Made changes to key.py
2. Check changes only to key.py file
3. Commit to master, I couldn't do a new branch to dev right away. I always got a merging error. 
4. Created new branch to dev 
5. Publish branch to Github
6. Merge jjex5 to dev.

**Comment by kstola2** [comment]
You're merging jjex05 to dev in this PR, not jjex5. Your jjex5 branch has blank keys and keys.test. Those need work done in them. You need to ignore master in this entire process. Dev branch is ahead of master currently by 15 commits so this PR has merge conflicts which I can't approve.

**Pull request closed without merging**
